baseurl = "https://badry.netlify.app/"
languageCode = "en-us"
title = "badriyah blog"
theme = "hugo-lithium"
googleAnalytics = "UA-4xxx"
disqusShortname = "badriyah"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Tentang"
    url = "/about/"
    [[menu.main]]
    name = "GitHub"
    url = "https://github.com/badriyah1705"
#[[menu.main]]
#   name = "Facebook"
#   url = "https://web.facebook.com/badriyah.jafar.5"
[[menu.main]]
    name = "Instagram"
    url = "https://www.instagram.com/badriyahzahirah/"

[params]
    description = "badriyah personal data blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

